language: python

python:
        - 3.6

services:
        - mysql


before_install:
        - mysql -e 'CREATE DATABASE IF NOT EXISTS flask_api_test;'
        - cd ./letitfly

install:
        - pip install -r ./requirements.txt

script: 
        - python ./manage.py test
